// Anonymous Entity Routing

export const EMAIL_CONFIG = {
  fromAddress: "Protocol Counsel Systems <support@protocolcounsel.com>",
  fromName: "Protocol Counsel Systems",
  scrubPatterns: [/Authorized by/i, /Managed by/i],
};

export function getEmailFooter() {
  return `Generated by ProtocolCounsel Automated Systems. This is a secure, system-mediated communication.

© ${new Date().getFullYear()} ProtocolCounsel | https://protocolcounsel.com`;
}

export function sanitizeContent(content: string) {
  let s = content;
  for (const p of EMAIL_CONFIG.scrubPatterns) s = s.replace(p, "Generated by");
  return s;
}